# Generated by Django 2.2.3 on 2019-07-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(default=None, max_length=7, unique=True),
        ),
    ]
