# Generated by Django 2.2.3 on 2019-07-13 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(blank=True, default=1, related_name='post_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
